config/routes.rb
Rails.application.routes.draw do
  
  resources :services, :reservations
  

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  resources :users, only: [:destroy]# do
    resources :profiles, only: [:show, :edit, :update, :destroy]

  root 'welcome#landing'
  
  get 'welcome/landing', :as => :welcome_landing
  get 'home' => 'welcome#home'
  get 'about' => 'welcome#about'

end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :reservations
  has_many :users, through: :reservations

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  
  def index
    @services = Service.all
  end
  
  def show
  end
  
  def new
    @service = Service.new
  end
  
  def edit
  end
  
  def create
    @service = Service.new(service_params)
    
    if @service.save
      redirect_to @service, notice: 'Service was successfully created.'
    else
      render :new
    
    end
  end
  
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end
  
  def destroy
    @service.destroy
    flash[:notice] = "'#{@service.name}' deleted."
    redirect_to services_path
  
  end
  
  
  private
    def set_service
      @service = Service.find(params[:id])
    end

    def service_params
      params.require(:service).permit(:name, :category, :location, :rating, :price)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/edit.html.haml
%h2 Edit Service
= form_tag @service, :method => :put do |f|
  = label :service, :name, 'Name', :class => 'col-form-label'
  = text_field :service, :name, :class => 'form-control'
  
  = label :service, :category, 'Category', :class => 'col-form-label'
  = text_field :service, :category, :class => 'form-control'
  
  = label :service, :location, 'Location', :class => 'col-form-label'
  = text_field :service, :location, :class => 'form-control'
  
  = label :service, :rating, 'Rating', :class => 'col-form-label'
  = text_field :service, :rating, :class => 'form-control'
  
  = label :service, :price, 'Price', :class => 'col-form-label'
  = select :service, :price, ['$','$$', '$$$', '$$$$'], {}, {:class => 'form-control col-1'}
  
  
  %br
  = submit_tag 'Update Service', :class => 'btn btn-primary'
  = link_to 'Cancel', services_path, :class => 'btn btn-secondary'

app/views/services/index.html.haml
%h3 Services
%p
  = link_to 'My Reservations', reservations_path, {class: "btn btn-primary"}
%br

%table{:style => "border:2px solid purple; width:100%;"}
  %thead
  %tbody
    %tr
      %th{:style => "border:2px solid purple; height: 70px; text-align:center;"} Name
      %th{:style => "border:2px solid purple; text-align:center;"} Category
      %th{:style => "border:2px solid purple; text-align:center;"} Location
      %th{:style => "border:2px solid purple; text-align:center;"} Rating
      %th{:style => "border:2px solid purple; text-align:center;"} Price
      %th{:style => "border:2px solid purple; text-align:center;"} Reservation
  
  - @services.each do |service|
    %tr
      %td{:style => "border:2px solid purple; text-align:center;"}
        = service.name
      %td{:style => "border:2px solid purple; text-align:center;"}
        = service.category
      %td{:style => "border:2px solid purple; text-align:center;"}
        = service.location
      %td{:style => "border:2px solid purple; text-align:center;"}
        = service.rating
      %td{:style => "border:2px solid purple; text-align:center;"}
        = service.price
      %td{:style => "border:2px solid purple; text-align:center;"} 
        = link_to 'Make Reservation', new_reservation_path(service), {class: "btn btn-danger"}

%br
%p
%hr
%table{:style => "border:1px solid black; width:100%;"}
  %b Services Data
  %tbody
    - @services.each do |service|
      %tr
        %th{:style => "border:1px solid black;"}
          = service.name
        %th{:style => "border:1px solid black;"}
          = link_to 'Edit Service', edit_service_path(service)
        %th{:style => "border:1px solid black;"}
          = link_to 'More info', service
        %th{:style => "border:1px solid black;"}
          = link_to 'Delete', service_path(service), 'data-method' => 'delete', 'data-confirm' => 'Delete service?'
  
  
%p  
  = link_to 'Add New Service', new_service_path

    

app/views/services/new.html.haml
%h2 Add New Service
= form_tag services_path do
  = label :service, :name, 'Name', :class => 'col-form-label'
  = text_field :service, :name, :class => 'form-control'
  
  = label :service, :category, 'Category', :class => 'col-form-label'
  = text_field :service, :category, :class => 'form-control'
  
  = label :service, :location, 'Location', :class => 'col-form-label'
  = text_field :service, :location, :class => 'form-control'
  
  = label :service, :rating, 'Rating', :class => 'col-form-label'
  = text_field :service, :rating, :class => 'form-control'
  
  = label :service, :price, 'Price', :class => 'col-form-label'
  = select :service, :price, ['$','$$', '$$$', '$$$$'], {}, {:class => 'form-control col-3'}
  
  
  %br
  = submit_tag 'Add Service', :class => 'btn btn-primary'
  %br
  = link_to 'Cancel', services_path, :class => 'btn btn-secondary'

app/views/services/show.html.haml
%h2 #{@service.name}

%ul#info
  %li
    %b Service:
    = @service.name
  %li
    %b Category:
    = @service.category
  %li
    %b Price:
    = @service.price
    
%h4 Details:

%p
  %b Location: 
  =@service.location
%p
  %b Rating:
  =@service.rating

%p 
= link_to 'Edit', edit_service_path(@service), :class => 'btn btn-primary'

= link_to 'Delete', service_path(@service), 'data-method' => 'delete', 'data-confirm' => 'Delete service?', :class => 'btn btn-secondary'

%p
= link_to 'Back', services_path