config/routes.rb
Rails.application.routes.draw do
  
  resources :services, :reservations
  

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  resources :users, only: [:destroy]# do
    resources :profiles, only: [:show, :edit, :update, :destroy]

  root 'welcome#landing'
  
  get 'welcome/landing', :as => :welcome_landing
  get 'home' => 'welcome#home'
  get 'about' => 'welcome#about'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :keep_out_unless_logged_in
  def landing
    @action = 'login'
  end
  
  def about
    @action = 'login'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.haml
%h3 About Modern Beauty
%p Modern Beauty provides services to customers based on their daily beauty needs.

%h3 The Team Behind Modern Beauty:
%p Selin Eylül Bilen, Nazlı Güler, Tomer Alon

%br
  = link_to "Back", home_path, {class: "btn btn-secondary"}

app/views/welcome/home.html.haml
%h2 For Your Daily Beauty Needs
%div
= image_tag "logo.png", :id=> "logo" '/'

%div
%br
  = link_to "Services", services_path, {class: "btn btn-primary"}
  = link_to "Reservations", reservations_path, {class: "btn btn-primary"}

app/views/welcome/index.html.haml
%h2 Modern Beauty
%h3 For Your Daily Beauty Needs

= button_to "Register or Login with GitHub", '/auth/github', {class: "btn btn-primary"}

//=link_to "Register or Login with GitHub", class: "btn btn-primary", '/auth/github'

app/views/welcome/landing.html.haml
%div
= image_tag "logo.png", :id=> "logo" '/'

%h3 For Your Daily Beauty Needs
= button_to "Register or Login with GitHub", '/auth/github', {class: "btn btn-primary"}