config/routes.rb
Rails.application.routes.draw do
  
  resources :services, :reservations
  

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  resources :users, only: [:destroy]# do
    resources :profiles, only: [:show, :edit, :update, :destroy]

  root 'welcome#landing'
  
  get 'welcome/landing', :as => :welcome_landing
  get 'home' => 'welcome#home'
  get 'about' => 'welcome#about'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :service

end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservation = Reservation.all	
  end

  def show
		id = params[:id]
    @reservation = Reservation.find(id)
  end

  def new
		@reservation= Reservation.create!(:time_in=>DateTime.now())	
	
		flash[:notice] = "You have made a reservation"
		redirect_to reservation_index_path(@reservation)
  end

  def edit
	end
	
  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      redirect_to @reservation, notice: 'Reservation created.'
    else
      render :new
    end
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservation_index_path, notice: 'Reservation updated.'
    else
      render :edit
    end
  end

  def destroy
    @reservation.destroy
    redirect_to services_index_path, notice: 'Reservation removed.'
  end

  private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:name, :category, :location, :rating, :price, :date, :user)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def index
    @reservations = Reservation.all	
  end

  def show
  end

  def new
    @reservation = Reservation.new	
  end

  def edit
	end
	
  def create
    @reservation = Reservation.new(reservation_params)

    if @reservation.save
      redirect_to @reservation, notice: 'Reservation created.'
    else
      render :new
      
    end
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservation_path, notice: 'Reservation updated.'
    else
      render :edit
    end
  end

  def destroy
    @reservation.destroy
    flash[:notice] = "Reservation removed."
    redirect_to services_path
  end

  private

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    def reservation_params
      params.require(:reservation).permit(:name, :service_location, :date)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/edit.html.haml
%h2 Edit Reservation
= form_tag @reservation, :method => :put do |f|
  = label :reservation, :name, 'Name', :class => 'col-form-label'
  = text_field :reservation, :name, :class => 'form-control'
  
  = label :reservation, :service_location, 'Location', :class => 'col-form-label'
  = text_field :reservation, :service_location, :class => 'form-control'
  
  = label :reservation, :date, 'date', :class => 'col-form-label'
  = datetime_local_field :reservation, :date, :class => 'form-control'
  
  
  %br
  = submit_tag 'Update Reservation', :class => 'btn btn-primary'
  %br
  = link_to 'Cancel', reservations_path, :class => 'btn btn-secondary'

app/views/reservations/index.html.haml
%h3 Reservations

%h4 Your Reservations:

%table{:style => "border:2px solid purple; width:100%;"}
  %thead
  %tbody
    %tr
      %th{:style => "border:2px solid purple; height: 70px; text-align:center;"} Name
      %th{:style => "border:2px solid purple; text-align:center;"} Location
      %th{:style => "border:2px solid purple; text-align:center;"} Date
      %th{:style => "border:2px solid purple; text-align:center;"} Manage

  - @reservations.each do |reservation|
    %tr
      %td{:style => "border:2px solid purple; text-align:center;"}
        = reservation.name
      %td{:style => "border:2px solid purple; text-align:center;"}
        = reservation.service_location
      %td{:style => "border:2px solid purple; text-align:center;"}
        = reservation.date
      %td{:style => "border:2px solid purple; text-align:center;"}
        = link_to 'Edit Reservation', edit_reservation_path(reservation)
        %br -
        = link_to 'Delete', reservation_path(reservation), 'data-method' => 'delete', 'data-confirm' => 'Delete reservation?'
        

%br
%p
  = link_to 'Back to Services', services_path, {class: "btn btn-secondary"}

app/views/reservations/new.html.haml
%h2 Make New Reservation
= form_tag reservations_path do
  = label :reservation, :name, 'Name', :class => 'col-form-label'
  = text_field :reservation, :name, :class => 'form-control'
  
  = label :reservation, :service_location, 'Location', :class => 'col-form-label'
  = text_field :reservation, :service_location, :class => 'form-control'
  
  = label :reservation, :date, 'Date', :class => 'col-form-label'
  = datetime_local_field :reservation, :date, :class => 'form-control'
  
  %br
  = submit_tag 'Confirm', :class => 'btn btn-success'
  %br
  = link_to 'Cancel', services_path, :class => 'btn btn-secondary'

app/views/reservations/show.html.haml
%h2 #{@reservation.name}

%ul#info
  %li
    %b Reservation for:
    = @reservation.name
    
%h4 Details:

%p
  %b Location: 
  =@reservation.service_location
%p
  %b Date:
  =@reservation.date

%p 
= link_to 'Edit', edit_reservation_path(@reservation), :class => 'btn btn-primary'

= link_to 'Delete', reservation_path(@reservation), 'data-method' => 'delete', 'data-confirm' => 'Delete reservation?', :class => 'btn btn-secondary'

%p
= link_to 'Back', reservations_path