config/routes.rb
Rails.application.routes.draw do
  
  resources :services, :reservations
  

  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/start_test'
  get 'sessions/clear'
  get 'session/debug'

  resources :users, only: [:destroy]# do
    resources :profiles, only: [:show, :edit, :update, :destroy]

  root 'welcome#landing'
  
  get 'welcome/landing', :as => :welcome_landing
  get 'home' => 'welcome#home'
  get 'about' => 'welcome#about'

end

app/views/layouts/_flash.html.haml
- if flash[:notice]
  #notice.alert.alert-info{role: "alert"}
    = flash[:notice]
- elsif flash[:warning]
  #warning.alert.alert-danger{role: "alert"}
    = flash[:warning]

app/views/layouts/_footer.html.haml
- unless @action == 'login'
  =link_to "Home", home_path
  |
  =link_to "About", about_path
  %p
  = button_to "Log Out", logout_path, {class: "btn btn-secondary"}

app/views/layouts/application.html.haml
!!!
%html
  %body
    %title Modern Beauty
    %link{crossorigin: "anonymous", href: "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css", integrity: "sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z", rel: "stylesheet"}/
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %nav.navbar.navbar-light{:style => "background-color: #dea5a5;"}
      %h1.title Modern Beauty
    .container
      = render 'layouts/flash'
      %main#main
        = yield
        
    .footer
      = render 'layouts/footer'
          